services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'app_db'
      MYSQL_USER: 'app_user'
      MYSQL_PASSWORD: 'app_password'
      MYSQL_ROOT_PASSWORD: 'root_password'
    ports:
      - "3306:3306"
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d

  api:
    build:
      context: ./DotnetBestPractices
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=app_db;User=app_user;Password=app_password;
    depends_on:
      - db

  frontend:
    build:
      context: ./angular-best-practices
      dockerfile: Dockerfile
    ports:
      - "4200:80" # Mapping local port 4200 to Nginx port 80
    depends_on:
      - api
